User documentation for the new decompiler {Do not merge}
radareorg/cutter pull request #2394
Opened 2020-08-17 14:43 UTC by NirmalManoj

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
This is the documentation for the new context menu for the decompiler implemented by PR #2391 . 

**Test plan (required)**
1. Read all the documentation. Think if anything can be improved.
2. Make sure I didn't miss out anything.

**Closing issues**

2020-08-20 10:56 UTC, ITAYC0HEN commented
Didn't review yet.

But I expect a real user documentation and not only menu reference. Means, a dedicated "r2book"-like page for the decompiler widget. Yes, the decompilers are different from each other and we only provide the interface, and still.

See for example Ghidra's. Partial screenshot:
![image](https://user-images.githubusercontent.com/20182642/90761095-90a2c600-e2eb-11ea-8ef4-8c5c65d3ea61.png)

Full source:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/main/help/help/topics/DecompilePlugin/Decompiler.htm


and there are few nice things in IDA's
https://www.hex-rays.com/products/decompiler/compare/compare_vs_disassembly/
https://www.hex-rays.com/products/decompiler/manual/index.shtml



I also expect to refer the readers to available decompilers -> https://github.com/radareorg/cutter-plugins#decompilers

Also to mention that r2ghidra is the official plugin maintained but the devs of cutter and r2.
I also would like to see some tips for how to create a new decompiler. I'd like to see the information for devs about the structure of the annotations (maybe better to be put in a mutual place with r2).

Also to show how it can work with debugger and list common issue s(oh boy there are...), how it can be synced with the disassembly, and more and more. I want the reader to go to a journey in a book to understand the decompiler in cutter.


As it is now, I think it is far from enough. It is simply a context menu reference...

2020-08-20 12:07 UTC, karliss requested changes

2020-08-20 19:34 UTC, NirmalManoj commented
@ITAYC0HEN Where do you want such a page that introduces the Cutter's decompiler to appear?


> also would like to see some tips for how to create a new decompiler. I'd like to see the information for devs about the structure of the annotations

I can explain the structure of the annotations. But what did you actually mean by the second sentence?

2020-08-24 12:50 UTC, NirmalManoj commented
> I know @karliss might have different opinions so let's hear it before you move forward for the dev documentation (user docs should proceed as discussed)

@karliss Do you have different opinions on the documentation for developers?

2020-08-25 13:59 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu/debug-context-menu.rst
> +Debug Context Menu
Added this as a section under the decompiler-context-menu page and removed these files.

2020-08-25 13:59 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Shortcut:** :kbd:`Ctrl` + :kbd:`C`
Changed as suggested.

2020-08-25 13:59 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu/debug-context-menu.rst
> +**Steps:** While in Debug or Emulation modes, right-click and address and choose ``Debug -> Continue until line``.
Fixed

2020-08-26 17:12 UTC, ITAYC0HEN requested changes
Very nice Nirmal! :)

I will have more review comments, especially about `features.rst`

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Add a comment in the location under the cursor or edit the comment in the location under the cursor. Edit comment option is available only for user defined comments.
```suggestion
**Description:** Add a comment in the location under the cursor or edit the comment in the location under the cursor. The ``Edit Comment`` option is only available for user defined comments.
```

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click and choose `Add Comment` or `Edit Comment`.
need to use double backtics

```suggestion
**Steps:** Right-click and choose ``Add Comment`` or ``Edit Comment``.
```


Check all other places for the same mistake

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the function name and choose ``Rename function <name of function>``
```suggestion
**Steps:** Right-click on a function name and choose ``Rename function <name of function>``  
```

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the global variable and choose ``Add name to <address of global variable>`` or ``Rename [name]``.
mixed `<placeholder>` and `[placeholder]`

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the global variable and choose ``Remove [name of global variable]``.
also, notice the mixture of `<placeholder>` and `[placeholder]` please also check it across the PR

```suggestion
**Steps:** Right-click on a global variable and choose ``Remove [name of global variable]``.
```

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the variable and choose ``Rename variable [name]``.
```suggestion
**Steps:** Right-click on a variable and choose ``Rename variable [name]``. 
```

this mistake is repeating, please check across the entire PR

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Rename or set the types of the function's variables and arguments. Note that this option is available only for function variables defined in the disassembly.
```suggestion
**Description:** Rename or set the types of the function's variables and arguments. Note that this option is available only for function variables and arguments defined in the disassembly.
```

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Add a breakpoint at the earliest offset in the line under the cursor. If you use the shortcut and if multiple breakpoints are present in a line, all of them will be removed.
```suggestion
**Description:** Add a breakpoint at the earliest offset in the line under the cursor. If you use the keyboard shortcut to remove a breakpoint, all the breakpoints defined in the line will be removed.
```

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Open the advanced breakpoint dialog. This dialog lets you define not only a regular breakpoint in this address, but also a Hardware breakpoint, a conditional breakpoint, and more.
Either "**H**ardware breakpoint" and "**C**onditional breakpoint" or don't capitalize any

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click on an instruction and choose ``Breakpoint -> Advanced breakpoint``. If multiple breakpoints are present in the line, you will be able choose the breakpoint you want to edit fro
see :menuselection: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-menuselection

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** While in Debug or Emulation modes, right-click and address and choose ``Debug -> Continue until line``.
```suggestion
**Steps:** While in Debug or Emulation modes, right-click on an address and choose ``Debug -> Continue until line``.  
```

2020-08-26 17:12 UTC, ITAYC0HEN commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** While in Debug or Emulation modes, right-click and address and choose ``Debug -> Continue until line``.
see :menuselection:

2020-08-27 03:27 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Set the Program Counter of the debuger to the current offset. For example, on an Intel 64bit program, Cutter will set the value of the RIP register to the current address.  *This opt
```suggestion
**Description:** Set the Program Counter of the debugger to the current offset. For example, on an Intel 64bit program, Cutter will set the value of the RIP register to the current address.  *This option is only available on Debug or Emulation modes*.  
```

2020-08-27 12:49 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Set the Program Counter of the debuger to the current offset. For example, on an Intel 64bit program, Cutter will set the value of the RIP register to the current address.  *This opt
Changed as suggested.

2020-08-27 12:49 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** While in Debug or Emulation modes, right-click and address and choose ``Debug -> Continue until line``.
Changed as suggested.

2020-08-27 12:50 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click on an instruction and choose ``Breakpoint -> Advanced breakpoint``. If multiple breakpoints are present in the line, you will be able choose the breakpoint you want to edit fro
Changed as suggested.

2020-08-27 12:50 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Open the advanced breakpoint dialog. This dialog lets you define not only a regular breakpoint in this address, but also a Hardware breakpoint, a conditional breakpoint, and more.
Made it lower case.

2020-08-27 12:50 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Add a breakpoint at the earliest offset in the line under the cursor. If you use the shortcut and if multiple breakpoints are present in a line, all of them will be removed.
Changed as suggested.

2020-08-27 12:50 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Rename or set the types of the function's variables and arguments. Note that this option is available only for function variables defined in the disassembly.
Changed as suggested.

2020-08-27 12:51 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the variable and choose ``Rename variable [name]``.
Fixed in multiple places in the document. Please check again.

2020-08-27 12:51 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the global variable and choose ``Remove [name of global variable]``.
Checked across PR.

2020-08-27 12:52 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click the function name and choose ``Rename function <name of function>``
Changed.

2020-08-27 12:52 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:** Right-click and choose `Add Comment` or `Edit Comment`.
Changed as suggested.

2020-08-27 12:52 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Add a comment in the location under the cursor or edit the comment in the location under the cursor. Edit comment option is available only for user defined comments.
Changed as suggested.

2020-08-27 12:52 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +Show the code in another widget
I could find this only one location iirc. Please check again.

2020-08-27 12:52 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:**  Right-click on an item and choose the ``Show [item] in`` sub-menu.
Fixed.

2020-08-27 12:53 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:**  Right-click on an item and choose the ``Show in`` sub-menu.
Rephrased to ```Right-click on an item and go to the :menuselection:`Show in` submenu. You can choose a widget or open a new widget from here.```

2020-08-27 12:54 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:**  Right-click on a location and choose ``Copy  address of [<name of reference>](<address>)``
Changed. Please check now.

2020-08-27 12:55 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** If text is selected, copy selected text. Otherwise, if a word is highlighted, copy that word. In all other cases, copy the line under the cursor.
Changed as suggested.

2020-08-27 12:57 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Steps:**  Right-click on a location and choose ``Copy instruction address(<address>)``
Rephrased to ```Copy the address of the instruction mapped to the part of code under the cursor.```

2020-08-28 03:26 UTC, Surendrajat requested changes
Hail Grammarly :)

2020-08-28 03:26 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Copy the address of the instruction mapped to the part of code under the cursor.
```suggestion
**Description:** Copy the address of the instruction mapped to the part of the code under the cursor.
```

2020-08-28 03:26 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Copy the address of the reference under cursor. References include functions, global variables, and constant variables with an address.
```suggestion
**Description:** Copy the address of the reference under the cursor. References include functions, global variables, and constant variables with an address.
```

2020-08-28 03:26 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Add a comment in the location under the cursor or edit the comment in the location under the cursor. The ``Edit comment`` option is only available for user defined comments.
```suggestion
**Description:** Add a comment in the location under the cursor or edit the comment in the location under the cursor. The ``Edit comment`` option is only available for user-defined comments.
```

2020-08-28 03:26 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Delete the comment at the location under the cursor. This option is only available for user defined comments.
```suggestion
**Description:** Delete the comment at the location under the cursor. This option is only available for user-defined comments.
```

2020-08-28 03:26 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Show X-Refs to the reference under cursor. This option will open Cutter's X-Refs dialog in which you will be able to see a list of X-Refs from and to the address of the reference. Yo
```suggestion
**Description:** Show X-Refs to the reference under the cursor. This option will open Cutter's X-Refs dialog in which you will be able to see a list of X-Refs from and to the address of the reference. You can also see a preview of each cross-reference to quickly inspect the different usages. Note that references refer to function names, global variables, and constant variables with an address.  
```

2020-08-28 03:26 UTC, Surendrajat commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +Delete the name of global variable
```suggestion
Delete the name of a global variable
```

2020-08-28 12:47 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +Delete the name of global variable
Changed as suggested.

2020-08-28 12:48 UTC, NirmalManoj commented on docs/source/user-docs/menus/decompiler-context-menu.rst
> +**Description:** Show X-Refs to the reference under cursor. This option will open Cutter's X-Refs dialog in which you will be able to see a list of X-Refs from and to the address of the reference. Yo
Changed as suggested. This and every other suggestion you have made.

2020-08-29 09:56 UTC, karliss commented
> @karliss Do you have different opinions on the documentation for developers?

I have no objections against having a page in developer docs describing high level structure of decompiler in cutter and R2. What are the components involved, what are their main responsibilities and how they communicate with each other.

It shouldn't duplicate the API documentation and try to describe each method or each annotation. It doesn't need to be a tutorial for people who can barely program.

To summarize here is what I would like to see for developer docs:
* Document the Decompiler interface using doxygen
* Page in developer docs describing high level structure of decompiler in Cutter
   * What are the components involved (r2 plugin, r2, Cutter, Cutter plugin[cutter plugin impl, Cutter Decompiler impl])
   * Role of each component. Described using human language instead of literal translation code into English.  Description like "This module calls this function, then it calls that function using the result function and then it calls one more function" is in my opinion worse than no documentation and reading the code directly. At least when reading the code it's up to date.
   * How the components communicate with each other, at high level, details should be in API docs
   * Checklist of what needs to be implemented (Cutter Plugin,Cutter Decompiler, r2 plugin optional but recommended)

2020-08-29 11:47 UTC, NirmalManoj commented
@ITAYC0HEN I am not sure if I could make developer documentation in the next two days like Karliss wants. So I'm thinking of doing it after my project in another PR. User documentation is important, so I don't want developer doc to block this PR from getting merged.

2020-08-30 11:11 UTC, ITAYC0HEN commented
@NirmalManoj this is fine :) I prefer you relaxed and focused on the things you must do, rather then submitting ahlf-baked dev docs. So, no problems - let's keep dev docs for a following PR :)

2020-08-30 13:13 UTC, ITAYC0HEN approved these changes

2020-08-30 13:14 UTC, NirmalManoj commented on docs/source/user-docs/features.rst
> +utilities and vies that be used and controlled by you during your session. As more familiar and comfort you feel with the
*views

2020-08-30 13:18 UTC, NirmalManoj commented on docs/source/user-docs/features.rst
> +utilities and vies that be used and controlled by you during your session. As more familiar and comfort you feel with the
utilities and _views_ that _can_ be used and

2020-08-30 13:22 UTC, ITAYC0HEN commented on docs/source/user-docs/features.rst
> +utilities and vies that be used and controlled by you during your session. As more familiar and comfort you feel with the
```suggestion
utilities and views that be used and controlled by you during your session. As more familiar and comfort you feel with the
```

2020-08-30 14:12 UTC, NirmalManoj commented on docs/source/user-docs/features.rst
> +utilities and vies that be used and controlled by you during your session. As more familiar and comfort you feel with the
Shouldn't it be _that **can** be_?

2020-08-30 14:28 UTC, ITAYC0HEN commented on docs/source/user-docs/features.rst
> +utilities and views that be used and controlled by you during your session. As more familiar and comfort you feel with the
```suggestion
utilities and views that can be used and controlled by you during your session. As more familiar and comfort you feel with the
```

2020-08-31 06:04 UTC, karliss approved these changes

2020-08-31 06:50 UTC, Surendrajat approved these changes

2020-08-31 06:53 UTC, merged