Make the Decompiler Widget Synchronized like other widgets and remove auto refresh.
radareorg/cutter pull request #2402
Opened 2020-08-20 19:25 UTC by NirmalManoj

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
This PR removes the auto-refresh feature and refresh button from the decompiler widget. It is replaced by the sync-able widget mechanism which will make its operations just like how the other widgets work.

_Here's how it looks now_:
![Screenshot from 2020-08-21 00-44-24](https://user-images.githubusercontent.com/18501167/90815218-f9b82700-e347-11ea-96f8-50c058c6ff87.png)

**Test plan (required)**
1. "sync/unsync" works as intended
2. Show in decompiler works and doesn't affect global seek when not synchronized
3. Decompiler gets refreshed when required(changes to breakpoints, instructions, comments, ..) when not in sync.
4. Check code and make sure that I have removed every piece code related to the previous auto-refresh mechanism.

**Closing issues**
closes #2370

2020-08-20 21:57 UTC, NirmalManoj commented
I think this PR can also have code to close issue #1766 

Three decompiler widgets open each with _different_ decompiler!
![Screenshot from 2020-08-21 03-22-16](https://user-images.githubusercontent.com/18501167/90829829-25dea280-e35e-11ea-9567-17c28a7b284d.png)

2020-08-21 04:38 UTC, ITAYC0HEN commented on src/widgets/DecompilerWidget.h
> +    void refreshForChange(RVA addr);
I don't like this name. let's come up with a better one

2020-08-21 05:17 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.h
> +    void refreshForChange(RVA addr);
Sure, `refreshFunctionIfModified()`, `refreshFunction()`, `refresh()`?

2020-08-21 07:11 UTC, karliss commented on src/widgets/DecompilerWidget.h
> +    void refreshForChange(RVA addr);
`refreshIfChanged(addr)` ?

2020-08-24 11:12 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.h
> +    void refreshForChange(RVA addr);
I have changed this to `refreshIfChanged`

2020-08-24 11:13 UTC, NirmalManoj commented
> @NirmalManoj do you want to do them in the same PR? we can go one by one in order to make the review faster.
> What do you prefer?

I actually confused this PR for the documentation PR earlier. Sorry about the confusion @ITAYC0HEN . Yes, I want them in the same PR.

2020-08-24 11:17 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Why do you need to disconnect and reconnect the signal each time?

2020-08-24 11:21 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Because `RAnnotatedCode` is owned by the decompiler widget. When multiple decompiler widgets are there, each needs it's own `RAnnotatedCode` structure.

2020-08-24 11:22 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
If you are trying to deal with multiple decompiler widgets interacting with the same decompiler, it won't be that easy. You might need to to split multiple decompiler widget support into separate issue.

2020-08-24 11:26 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Can you elaborate on what you mean by that? Connecting and disconnecting signals each time we want to refresh a decompiler seems to be working well.

2020-08-24 11:33 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Here, the problem is mainly with memory deallocation. Assume we have two decompiler widgets in sync with the same `RAnntoatedCode`, suppose I go to a different function. Then one decompiler frees it and the other one also tries to free it. This leads to memory problems. This is one of the problems we could overcome with a connect-disconnect here.

2020-08-24 11:36 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
The connect-disconnect mechanism ensures that each decompiler will have its own unique `RAnnotatedCode`.

2020-08-24 12:53 UTC, NirmalManoj commented on src/core/Cutter.cpp
>  /**
(Not related to the lines selected)
I will be removing the decompiler checkbox and will instead add an `Add Decompiler` option in Windows menu.

2020-08-24 13:47 UTC, NirmalManoj commented on src/core/MainWindow.cpp
> +    extraDock->updateWindowTitle();
The title of Hexdump, Graph, and the Disassembly were not updated to be the correct one with numbering when they are added from the Windows menu. This line fixes this problem.

**Before**
![Disassembly numbering gone wrong](https://user-images.githubusercontent.com/18501167/91051828-48aed680-e63e-11ea-99e1-c42f4e9207cb.gif)
**After**
![Widget naming fixed](https://user-images.githubusercontent.com/18501167/91051860-506e7b00-e63e-11ea-81c8-fa5857253475.gif)

2020-08-24 17:57 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Finally the part where I warned you during beginning of summer that this is a bad API which makes it difficult to use correctly is catching up.

I assume that by decompiler you meant decompiler widget not the the decompiler. Freeing the memory is only half of problem. The bigger problem that the Decompiler API isn't suitable for interacting with multiple users at the same time. It would be better if it returned something like std::future or qfuture, but that should better be done together with rest of Cutter/R2task async refectoring so that it's consistent with that.

For now there is the `dec->isRunning()` check. I didn't notice when writing comment above because it wasn't visible in the context shown by GitHub. Assuming `DecompilerWidget:doRefresh()` always gets called in GUI thread that's good enough, but there are some small adjustments that could be done.

Current `decompilerWasBusy` logic doesn't make any sense. It isn't really used anywhere. Also in the case that refresh gets ignored do to decompilation running which was triggered by other decompiler widget the second refresh will get lost. In my opinion it should retry latter in such situation. This can probably only be observed using two decompiler widgets using retdec because r2ghidra decompilation currently is blocking which is a regression compared the state before summer.
The process for reproducing the problem might be something like this:
* have two desynchronized decompiler widgets both using retdec
* show in decompiler 1 using large function that takes a while to decompile
* quickly before first function finishes decompiling do show in decompiler2
If my assumptions are correct second decompiler widget will not get refreshed even after the first decompiler finishes. Unless the new decompilation is started after the first one finishes.  It might be even simpler to trigger this by having two synchronized decompiler using retdec. That would seek would then cause both of them to attempt decompiling quickly one after another and the order doesn't matter in this case. It wouldn't be very useful having two identical decompiler widgets that are synchronized and use the same decompiler, but it's a way for observing the problem.

2020-08-24 18:05 UTC, karliss commented on src/core/MainWindow.cpp
> +    extraDock->updateWindowTitle();
I think this would be better done within constructor after the call to `setObjectName`. Graph view already does this. That way you it is less likely to break if new place creating them gets added.

2020-08-24 18:15 UTC, karliss commented on src/core/MainWindow.cpp
> +    extraDock->getSeekable()->seek(Core()->getOffset());
It should be sufficient to just refresh here.

2020-08-24 18:21 UTC, NirmalManoj commented on src/core/MainWindow.cpp
> +    extraDock->updateWindowTitle();
Changed as suggested.

2020-08-24 18:32 UTC, NirmalManoj commented on src/core/MainWindow.cpp
> +    extraDock->getSeekable()->seek(Core()->getOffset());
Do we want to open the new decompiler widget in sync or not in sync? Currently, it is opening in sync. In that case, no line is required here.

2020-08-25 09:34 UTC, karliss commented on src/core/MainWindow.cpp
> +    extraDock->getSeekable()->seek(Core()->getOffset());
I think it's fine for it to be in sync when opened from main menu.  The main reason "show-in/new x" opens the widget without sync is so that you can open new widget showing something else without loosing current position. In this case the position would be the same as current seek so it woudn't be lost and even if you click around you do some clicks you wouldn't be too far. There were some discussions on this topic when the feature was added.

2020-08-25 10:20 UTC, NirmalManoj commented on src/core/MainWindow.cpp
> +    extraDock->getSeekable()->seek(Core()->getOffset());
I have removed this line.

2020-08-25 10:35 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Your assumptions are correct, r2dec doesn't work when multiple widgets have it in sync. A gif displaying this problem:
![r2dec-not-working](https://user-images.githubusercontent.com/18501167/91163413-27f08a80-e6eb-11ea-908a-2396c6b6dd3a.gif)
Also, r2ghidra-dec is working because it blocks parallel execution as you said. Before summer, r2ghidra-dec's decompilation was executed as an `R2Task`, and the output was parsed from JSON just like it happens right now in r2dec.

Could you give some ideas on how I can efficiently make it retry in such situations?

2020-08-25 11:08 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
I tried the second approach, seem to be working without problems. Please check.

![r2dec-fixed](https://user-images.githubusercontent.com/18501167/91167259-49547500-e6f1-11ea-9b96-899b0f8762f4.gif)

2020-08-25 11:50 UTC, ITAYC0HEN commented on src/widgets/DecompilerWidget.cpp
> +        ui->textEdit->setPlainText(tr("A function doesn't exist at the selected offset in this decompiler."));
In this decompiler?
Isn't it about what r2 detected?

2020-08-25 13:10 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +        ui->textEdit->setPlainText(tr("A function doesn't exist at the selected offset in this decompiler."));
Actually in this case, it is just invalid offset.  I'll change this to ```
Invalid offset for a function
```

2020-08-25 18:21 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +        ui->textEdit->setPlainText(tr("A function doesn't exist at the selected offset in this decompiler."));
Changed this message to
``` Decompiler Error: No function at this offset ```

2020-08-25 19:00 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
If you do it that way there is no need to introduce second signal. You can do exactly the same using the old signal without changing API.

Your current code doesn't work correctly if decompiler selection changes between between the first refresh getting delayed and handling decompileComplete signal.

2020-08-26 10:35 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
I can disable the option to change to decompilers when a widget is waiting to get decompiled.

2020-08-26 12:34 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
I have disabled the option to change decompilers when a widget is waiting to get decompiled.

2020-08-26 16:18 UTC, ITAYC0HEN commented on src/widgets/DecompilerWidget.cpp
> +            ui->decompilerComboBox->setEnabled(false);
add comment explaining the discussion and the reason behind it. Otherwise ppl just enable it because "why not"

2020-08-26 16:32 UTC, ITAYC0HEN requested changes
Please add the function name to the title as can be seen in Graph

![image](https://user-images.githubusercontent.com/20182642/91330906-bc81e800-e7d2-11ea-84fe-5e48575caaad.png)


Please add "(empty)" to the title when a decompiler isn't in a function. Similar to the graph

![image](https://user-images.githubusercontent.com/20182642/91330966-d4596c00-e7d2-11ea-866d-d3ec9ea926b4.png)

2020-08-26 16:33 UTC, ITAYC0HEN commented
In terms of functionality, it looks very good :)) Didn't experience any issue (and I tried! :P  )

Yet to look at the code

2020-08-26 18:45 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Can you explain what `decompilerWasBusy` means.

2020-08-26 20:23 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
As of now, `decompilerWasBusy` will be true if the decompiler selected in the decompiler widget is running decompilation for that widget. So it will tell if the decompiler is working for the widget we are in.

When `dec->isRunning() ` is true but `decompilerWasBusy` is false, that means `dec` is running in another widget so that we have to retry once that running decompilation gets finished.

As you pointed in a comment earlier, it's logic didn't do anything useful before.

2020-08-27 04:36 UTC, ITAYC0HEN commented on src/widgets/DecompilerWidget.cpp
> +        ui->textEdit->setPlainText(tr("A function doesn't exist at the selected offset in this decompiler."));
it's not an Error though. "Error" is a scary word we should use only when we encountered an issue on our side.

Here you can go for simply "No function at this offset" or eve add "No function found at this offset. Seek to a function or define one in order to decompile it."

2020-08-27 04:59 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +            ui->decompilerComboBox->setEnabled(false);
How about moving this code outside the if so that is shared by both cases the one where refresh gets delayed and the good case where decompilation gets started immediately.

2020-08-27 05:04 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
If it wasn't obvious does the name of this variable match the description you said?

2020-08-27 11:21 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    QObject::disconnect(dec, &Decompiler::finished, this, &DecompilerWidget::decompilationFinished);
Changed it to `decompilerBusy` and documented the variable properly.

2020-08-27 11:21 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +        ui->textEdit->setPlainText(tr("A function doesn't exist at the selected offset in this decompiler."));
Changed to `No function found at this offset. Seek to a function or define one in order to decompile it.`

2020-08-27 11:23 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +            ui->decompilerComboBox->setEnabled(false);
I have moved code outside and refactor this function a bit.

2020-08-27 11:23 UTC, NirmalManoj commented
> Please add the function name to the title as can be seen in Graph

@ITAYC0HEN Done.

2020-08-27 11:29 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
>      }
I noticed an issue where the decompiler seeks again when the seek had been set by the other widgets. So if the seek from the disassembly was to a nop instruction after a function, the decompiler was seeking to the beginning of the function. Similar problems existed because `cursorPositionChanged` was getting called when the seek is set by other widgets.

2020-08-27 11:34 UTC, ITAYC0HEN commented on src/widgets/DecompilerWidget.cpp
>      }
good catch. what is the solution?

2020-08-27 11:38 UTC, ITAYC0HEN requested changes

2020-08-27 11:38 UTC, ITAYC0HEN commented on src/widgets/DecompilerWidget.cpp
> +    ui->decompilerComboBox->setEnabled(false);
Similar to my previous comment (I think). Add a comment here explaining why you disable it. Otherwise, in X months someone will come at enable it by mistake

2020-08-27 11:39 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    ui->decompilerComboBox->setEnabled(false);
I will do that.

2020-08-27 19:02 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
>      }
This is the solution:-) I will refactor this a little bit in an upcoming commits.

2020-08-27 19:13 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +    ui->decompilerComboBox->setEnabled(false);
Done.

2020-08-27 19:13 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
>      }
Done.

2020-08-28 12:17 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +        connectCursorPositionChanged(true);
It is very confusing that `connectCursorPositionChanged(true)` disconnects and `connectCursorPositionChanged(false)` restores the connections.

2020-08-28 12:27 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +        connectCursorPositionChanged(true);
I agree I will change it.

2020-08-28 12:43 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +        connectCursorPositionChanged(true);
Done.

2020-08-28 18:09 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +        connectCursorPositionChanged(true);
You forgot to update name in docstring.

2020-08-28 18:12 UTC, karliss approved these changes
Except the outdated docstring looks good to me.

2020-08-28 19:06 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +        connectCursorPositionChanged(true);
Updated docstring.

2020-08-28 20:52 UTC, ITAYC0HEN approved these changes
good work!

2020-08-29 05:15 UTC, merged