Add more options to the Analysis widget
radareorg/cutter pull request #2405
Opened 2020-08-25 19:09 UTC by ocastejon

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This MR adds the remaining options to the Analysis Widget that were proposed by @ITAYC0HEN in https://hackmd.io/@Megabeets/H1jBD3Hxv/edit, which are:

- `anal.in`
- `anal.prelude`
- `anal.ptrdepth`

For the `anal.in` option, I selected the following options only:

- All executable maps (`io.maps.x`)
- All maps (`io.maps`)
- Current map (`io.map`)
- Raw (`raw`)
- Current block (`block`)
- Current mapped section (`bin.section`)
- All mapped sections (`bin.sections`)

However, if you think other options should be there, I can add them too.

**Test plan (required)**

1. Open Cutter and go to Edit -> Preferences - > Analysis
2. Select one or more options in the drop-down "Search boundaries for analysis" and check with the console that the value of `anal.in` changes accordingly
3. Change the value of the option "Pointer depth" and check with the console that the value of `anal.ptrdepth` changes accordingly
4. Change the value of the option "Prelude" and check with the console that the value of `anal.prelude` changes accordingly
5. Close and reopen the dialog, and check that the last selected values for these options are maintained

![anal-options-2](https://user-images.githubusercontent.com/26287552/91216870-eece0f80-e716-11ea-8090-51a521ab8130.gif)

**Closing issues**

Closes #875

2020-08-27 05:02 UTC, ITAYC0HEN requested changes
Very nice job! :))
I suggested some changes

2020-08-27 05:02 UTC, ITAYC0HEN commented on src/dialogs/preferences/AnalOptionsWidget.ui
> +             <string notr="true">e.g.: 0x554889e5</string>
Are you sure it is `0xa1b2c3` and not `a1 b2 c3`? I have no idea personally
```suggestion
             <string notr="true">e.g.: 0x554889e5</string>
```

2020-08-27 05:02 UTC, ITAYC0HEN commented on src/dialogs/preferences/AnalOptionsWidget.ui
> +             <string notr="true">e.g.: 0x554889e5</string>
Also, I think it is very wise to add the place holder here, good job!

2020-08-27 17:22 UTC, ocastejon commented on src/dialogs/preferences/AnalOptionsWidget.h
> +    static void on_preludeLineEdit_textChanged(const QString &prelude);
You're totally right, I missed it. To fix it, in some cases I had to cast the signal to the right type (using `static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged)` for instance), which seems quite ugly to me. I saw that this was being done also in other parts of the code, so I guessed it should be all right.

2020-08-27 17:22 UTC, ocastejon commented on src/dialogs/preferences/AnalOptionsWidget.ui
> +           <widget class="QSpinBox" name="ptrdepthSpinBox">
Yep, I think so. Changed!

2020-08-27 17:26 UTC, ocastejon commented on src/dialogs/preferences/AnalOptionsWidget.ui
> +             <string notr="true">e.g.: 0x554889e5</string>
To be honest, I also had no idea, but according to the r2book this is the way:
``e anal.prelude = 0x554889e5``
(see the end of the section [Recursive Analysis](https://radare.gitbooks.io/radare2book/content/analysis/code_analysis.html#recursive-analysis))

2020-08-27 17:28 UTC, ocastejon commented on docs/source/user-docs/preferences/analysis.rst
> +Prelude
I also updated the label in the UI:

![image](https://user-images.githubusercontent.com/26287552/91475098-662cac00-e89b-11ea-8ff8-71cd1de9d6f2.png)

2020-08-28 04:18 UTC, ITAYC0HEN commented on src/dialogs/preferences/AnalOptionsWidget.ui
> +             <string notr="true">e.g.: 0x554889e5</string>
good enough :)

2020-08-28 12:29 UTC, karliss commented on src/dialogs/preferences/AnalOptionsWidget.cpp
> +    connect(ui->ptrDepthSpinBox, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), this,
For overloaded signals you can do this, which is slightly less verbose.
```suggestion
    connect<void (QSpinBox::*)(int)>(ui->ptrDepthSpinBox, &QSpinBox::valueChanged, this,
```

2020-08-28 18:36 UTC, ocastejon commented on src/dialogs/preferences/AnalOptionsWidget.cpp
> +    connect(ui->ptrDepthSpinBox, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), this,
Thanks, that is indeed somewhat nicer to read. I changed both the `ptrDepthSpinBox` and the `analInComboBox`. Thanks!

2020-08-30 13:16 UTC, ITAYC0HEN approved these changes

2020-08-30 13:17 UTC, merged

2020-08-30 13:17 UTC, ITAYC0HEN commented
Good work Oriol!