Save layout of the Decompiler Widgets
radareorg/cutter pull request #2410
Opened 2020-08-29 14:52 UTC by NirmalManoj

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
The decompiler widget was made sync-able and the support for multiple decompiler widgets was implemented by PR #2402. However, the layout management was not implemented in that PR, and because of this layouts were not restored. This PR aims to solve this issue.

Even though this PR will restore the layout, in case multiple widgets are open with multiple decompilers, all widgets will be opened with the last opened decompiler. The logic for implementing the ideal situation where the decompiler will also be restored will require complex refactorings. I don't intend to do that by this PR. This is not a big deal for now considering the fact that we are not restoring seek.

**Test plan (required)**
1. Compile PR and test if the layout gets restored as it should.
2. I'm not sure if there is anything else that I should add, so please have a quick look at how other memory widgets store and restore layouts and check if anything relevant is missing in this PR.

**Closing issues**

2020-08-29 15:06 UTC, karliss requested changes

2020-08-29 15:06 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +QString DecompilerWidget::getWidgetType()
It's probably better to use this when doing setObjectName so that they are in sync.

2020-08-29 15:09 UTC, karliss commented on src/widgets/DecompilerWidget.cpp
> +QString DecompilerWidget::getWidgetType()
Also object name shouldn't be translated it's an internal ID not a UI string.

2020-08-29 15:14 UTC, karliss commented
> The logic for implementing the ideal situation where the decompiler will also be restored will require complex refactorings. 

It shouldn't require a lot of refactoring. The mechanism for widget specific view setting saving is already there. All you have to do is implement `serializeViewProprties` and `deserializeViewProperties`.

2020-08-30 06:27 UTC, NirmalManoj commented on src/widgets/DecompilerWidget.cpp
> +QString DecompilerWidget::getWidgetType()
Thanks for pointing this out. Fixed it.

2020-08-30 06:29 UTC, NirmalManoj commented
> It shouldn't require a lot of refactoring. The mechanism for widget specific view setting saving is already there. All you have to do is implement `serializeViewProprties` and `deserializeViewProperties`.

Thanks for telling me. I will look into this and will see how this can be done. But not in this PR.

2020-08-30 06:59 UTC, karliss approved these changes
Looks good. I am investigating the travis failure. Unlikely to be related to your issue but needs to be fixed either way.

2020-08-30 11:26 UTC, merged

2020-08-30 12:12 UTC, ITAYC0HEN commented
how can we avoid such issues next times we add a widget? I would personally forget about it

2020-08-30 12:37 UTC, karliss commented
a) it only affects widgets with multiple copies, for others it's more difficult to get wrong
b) refactoring to reduce amount of code that needs to be updated
c) developer docs