Show comment column in each panel that have "add comment" option in the context menu
radareorg/cutter pull request #2441
Opened 2020-10-06 12:48 UTC by smhaziq

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
Added 'Comment' column to panels with Add comment context menu and with table content.

**Test plan (required)**
Change the comment of an address and see the comment column get updated across different panels listing the same address.

**Closing issues**
#927

2020-10-08 16:00 UTC, karliss requested changes
Since you are loading comment data in model on demand, in many cases it isn't necessary to reload all data when comment changes. It should be sufficient to trigger appropriate signal in in model so that table widget knows that it needs to refresh comment column for currently visible items.

It would be also useful to test if there is any performance impact on search for tables that can contain large amount of items. This is most likely to happen for function, flag, string widget.

2020-11-04 06:59 UTC, ITAYC0HEN commented
@smhaziq very nice work :)
Please let us know if you need more guidance with improving the things mentioned by Karliss, we would love to assist

2020-11-07 13:25 UTC, karliss commented
@smahziq Can you rebase your branch on top of upstream master so that it's clearer what are the change done by you? It currently looks weird almost as if you rebased upstream master on top of your branch.

2020-11-07 14:33 UTC, karliss requested changes

2020-11-07 14:33 UTC, karliss commented on src/widgets/ExportsWidget.cpp
> +    QModelIndexList matches = exportsModel->match(
Finding the matching rows requires iterating through all of them, negating the benefits of informing that only specific rows changed. 

`QAbstractItemModel::dataChanged` first two arguments are topLeft bottomRight so it's possible to notify about whole column changing in one go. So I suggest doing something like this
`emit model->dataChanged(index(row0, commentColumn), index(lastRow, commentColumn), ..)`

It may seem counterintuitive that telling that whole column changed is better than specific items, but you have to take into account cost of figuring out which items are those. In most cases telling that whole column changed should cause qt to only reload values for currently displayed rows in currently visible widgets, unless comment column is being used for sorting. In comparison current approach would require processing all rows in all models regardless of their visibility.

Also since implementation of this function will be more or less identical for all the models you could create a helper function `EmitColumnChanged(model, column)`.

Not relevant if you implement suggestion above, but keep in mind that DisplayRole is the string that will get displayed which might not be the best form for making decisions. For example column showing size in bytes might have string "1.25 KB" as display rule, but any comparison should better be done using actual number `1250`. Here you had similar situation instead of searching by address converted to string it would have been better to use a role which for given model returns number. It could be a custom user role but Cutter often uses Qt::EditRole for this since it also requires data in preferred format for manipulating with it.

2020-11-17 08:47 UTC, smhaziq commented on src/widgets/ExportsWidget.cpp
> +    QModelIndexList matches = exportsModel->match(
Thanks for the review. I've implemented the first suggestion.

2020-11-17 18:37 UTC, karliss commented on src/common/Helpers.cpp
> +        model->index(model->rowCount()-1, column),
Just to be safe I suggest checking if row count is greater than 0 thus avoiding somewhat questionable range `[0;-1]`

2020-11-18 03:17 UTC, smhaziq commented on src/common/Helpers.cpp
> +        model->index(model->rowCount()-1, column),
ok. I've added in null check as well

2020-11-18 09:44 UTC, karliss approved these changes
Looks good. I will see if CI can be quickly fixed before merging this.

2020-11-19 11:24 UTC, ITAYC0HEN approved these changes

2020-11-19 18:17 UTC, merged