Trackpad gesture support for graph views
radareorg/cutter pull request #2453
Opened 2020-10-21 14:52 UTC by 3c1u

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This adds the capability to handle pinch-to-zoom gesture to graph views using `QGestureEvent`.

**Test plan (required)**

1. Open a "Graph" view.
2. Do a pinch gesture on the track pad.
3. The scale of the view will change accordingly.

**Closing issues**

Closes #1377.

2020-10-21 21:22 UTC, karliss requested changes
Thank you for the pull request. Overall it doesn't looks quite good. On what operating system and hardware did you test this? 

I might give more comments once I test if I can get Qt to emit gesture events on the laptop I have.

2020-10-21 21:22 UTC, karliss commented on src/widgets/CutterGraphView.cpp
> +        QPointF cursorPos = mapFromGlobal(QCursor::pos());
I am slightly worried about grabbing global mouse position from `QCursor::pos` instead of using widget relative position provided by event. On some systems absolute window positions and probably accordingly mouse position is considered responsibility of window manager and each program individually should only operate with local information provided to them without knowing what happens locally.  Qt docs also partially warns about this.

There is QPinchGesture has hotSpot and centerPoint properties. Are any of those two usable for pinch zoom handling?

2020-10-21 21:22 UTC, karliss commented on src/widgets/GraphView.cpp
> +            return true;
QGestureEvent has methods for accepting each gesture individually in addition to returning boolen from event handler e and QEvent::accept used by rest of the events. Did you understood the docs for how it all works together?

2020-10-22 01:19 UTC, 3c1u commented
Thank you for the review. I tested on macOS 10.15.7, MacBook Pro (16-inch, 2019).
Now I applied the suggestions from your code review.

2020-10-22 01:22 UTC, 3c1u commented on src/widgets/CutterGraphView.cpp
> +                reinterpret_cast<QPinchGesture *>(event->gesture(Qt::PinchGesture))) {
`static_cast` surely worked!

2020-10-22 01:23 UTC, 3c1u commented on src/widgets/CutterGraphView.cpp
> +        setZoom(cursorPos, m_originalScale * m_currentScale);
Now it only updates when `ScaleFactorChanged` flag is on. I rewrote it using `scaleFactor` instead of `totalScaleFactor` so it became much simpler. (I initially thought that `scaleFactor` would return zero, but Qt internally calculates `totalScaleFactor` from scale factor, so it will be unlikely to happen.)

2020-10-22 01:25 UTC, 3c1u commented on src/widgets/GraphView.cpp
>  }
Now `grabGesture` is called in the `CutterGraphView` constructor. Should we move `GraphView::gestureEvent(QGestureEvent *event)` into `CutterGraphView`, too?

2020-10-22 01:25 UTC, 3c1u commented on src/widgets/CutterGraphView.cpp
> +        QPointF cursorPos = mapFromGlobal(QCursor::pos());
`centerPoint` worked!

2020-10-22 01:44 UTC, 3c1u commented on src/widgets/GraphView.cpp
> +            return true;
`QGestureEvent::accept(QGesture*)` is now called in `CutterGraphView::gestureEvent`. It is not necessary because a gesture is accepted by default.

2020-10-22 02:51 UTC, 3c1u commented on src/widgets/CutterGraphView.h
> +    qreal m_currentScale, m_originalScale;
Now those member variables are not used, and thus they are removed.

2020-10-28 18:22 UTC, karliss commented
The code looks good, but It would be good if anyone else with a macOS verified that it works as intended.

2020-11-03 06:03 UTC, ITAYC0HEN approved these changes
Thanks to @shakreiner we verified that it works on machine with trackpad ❤️

Great PR, thank you!

2020-11-03 06:21 UTC, karliss approved these changes

2020-11-03 06:23 UTC, merged