(WIP) Add preview functionality to DisassemblyWidget when hovering code, mu…
radareorg/cutter pull request #2459
Opened 2020-10-30 22:48 UTC by Petross404

…ch like Hopper does

**Your checklist for this pull request**
- [ x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

I have been experimenting with [Hopper](https://www.hopperapp.com/index.html) and I found a small feature that I liked. It's about previewing the code that is pointed by addresses and string constants when hovering the mouse above them. Hopper needs you to click on the code first in order to focus on the widget and then it can preview code. What I did was that I used the `QToolTip::showText` static function which doesn't need the `DisassemblyWidget` to have focus.

 So I discovered that the `FunctionsWidget` has what I am looking for. I 've read the code (I have to admit I reused a lot of it) and after tweaking to my purpose, the basic functionality is there. One problem I couldn't solve is that the preview is dark unlike the Disassembly Preview of the `FunctionsWidget`. I hope someone here can help me change this.

Right now the feature works but it lacks support in configuration (about colors, fonts, duration or even disabling it). I am willing to write and maintain this code if you think what I 've done here is nice.

**Test plan (required)**

I struggled to find a way so that the mouse won't show tooltips all around the place. Every command it pointed, triggered a preview. If the command didn't contain a `jmp` to some address or a `call` to some function, the tooltip would show the code in the current address the mouse was hovering.

I finally found a way to suppress the unnecessary tooltips. `readDisassemblyOffset(QTextCursor)` returns the current offset of the code that is under the mouse and that's why the tooltips printed every code I pointed. But in the `XrefDescription` info this function returns, I founded it contained both the offset `(RVA) from` where `readDisassemblyOffset` was called and the offset it pointed `to`.

So I shamelesly copied this snippet of code and I tweaked to suit my needs:
```cpp
        RVA offsetFrom, offsetTo = readDisassemblyOffset( cursorForWord );
        bool offsetsDiffer = false; //Do these 2 values differ?

        QList<XrefDescription> refs = Core()->getXRefs( offsetTo, false, false);
        if (refs.length()) {
            if (refs.length() > 1) {
                qWarning() << tr("More than one (%1) references here. Weird behaviour expected.")
                    .arg(refs.length());
            }
            offsetTo = refs.at(0).to;
            offsetFrom = refs.at(0).from;

            if( offsetTo != offsetFrom ){
                offsetsDiffer = true;
            }
        }
```

Basically what this code does is that after extracting the needed info about the offsets, it compares them and assign the boolean result to a variable. This variable is latter checked and if the offset **_from_** which this code path was triggered is different from the offset that we are pointing **_to_** (ie it won't preview the code at 0x0003f2 but rather it will preview the code at the offset 0x004f5 that is contained in the disassembly line at 0x0003f2).
![Screenshot_20201030_232726](https://user-images.githubusercontent.com/18561627/97761915-bd573300-1b0f-11eb-8f6c-6d566633e1cf.png)
![Screenshot_20201030_232812](https://user-images.githubusercontent.com/18561627/97761853-81bc6900-1b0f-11eb-8e57-74190511fb3a.png)
The original idea.
![Screenshot_20201030_233316](https://user-images.githubusercontent.com/18561627/97762063-20e16080-1b10-11eb-8ac8-4ba4a0602a19.png)

PS. I implemented this inside the `DisassemblyWidget::eventFilter(QObject *obj, QEvent *event)` for several reasons:
 * I didn't want to reimplement `mouseMoveEvent` because in the future we might want to do something else with it, so I chose the `eventFilter` function.
 * At first I used this:
```cpp
    else if (event->type() == QEvent::MouseMove
              &&  obj == mDisasTextEdit->viewport()) {
```
alongside with `setTracking` but the cursor couldn't left-click, drag and select more than one line. It felt weird and buggy. Not to mention that `QEvent::ToolTip` feels more appropriate for... well, a tooltip.
 * I began to write this code inside `DisassemblyTextEdit` widget which felt more natural to me, but soon I realized I needed various functions and data private to `DisassemblyWidget` class, so I abandoned the idea.

I failed to run astyle: 
```bash
 pwd
/home/petros/projects/CPlus/cutter
astyle --project=./src/Cutter.astylerc src/widgets/DisassemblyWidget.cpp 
Cannot open project option file ./src/Cutter.astylerc
Artistic Style has terminated
```

2020-10-31 07:13 UTC, Petross404 commented
Looking again at the code I though some small changes I could make. First I didn't initialize `RVA offsetFrom` to `RVA_INVALID`.

Second this code here
```cpp
            offsetTo = refs.at(0).to;
            offsetFrom = refs.at(0).from;

            if( offsetTo != offsetFrom ){
                offsetsDiffer = true;
            }
```
could make use of checking both values for `RVA_INVALID`. Also if these 2 variables are invalid and/or pointing to the same offset, there is no need to spend extra cpu and memory resources to construct fonts , stringlists, reading values from other functions and in order to fail in the last `if`.

Should I place the rest of the code inside an if-else?
```cpp
            if( offsetTo != offsetFrom ){
                offsetsDiffer = true;
                //move the code in here and show the tooltip
            } else {
                // should I return false to eventFilter or I should allow it to reach the 
                // return MemoryDockWidget::eventFilter(obj, event) line?
```

One last thing, this [line](https://github.com/radareorg/cutter/blob/master/src/widgets/DisassemblyWidget.cpp#L129) where the event filter is getting installed, might need an update in it's description.

2020-12-01 06:39 UTC, ITAYC0HEN commented
Hey @Petross404! We are deeply sorry for taking so much time to address your PR. Your details and explanations were great and you strictly followed the instructions and conventions we describe in the docs. The blame is on us.

I will address the PR today, and will ask other devs to have a look. Thank you so much!

2020-12-01 07:52 UTC, ITAYC0HEN requested changes
Looks very nice! This feature will be great in Cutter :)
I left some comments and suggestions

2020-12-01 07:52 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +        RVA offsetFrom, offsetTo = readDisassemblyOffset( cursorForWord );
```suggestion
        RVA offsetFrom, offsetTo = readDisassemblyOffset(cursorForWord);
```

2020-12-01 07:52 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +        QList<XrefDescription> refs = Core()->getXRefs( offsetTo, false, false);
I think it should be `offsetFrom`, right? as this produce the references **from** this address
```suggestion
        QList<XrefDescription> refs = Core()->getXRefs(offsetFrom, false, false);
```

2020-12-01 07:52 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +            offsetFrom = refs.at(0).from;
Here, you have `offsetFrom` defined already when you used `readDisassemblyOffset(cursorForWord);`. Thus you don't need to retrieve it once again

2020-12-01 07:52 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +        RVA offsetFrom, offsetTo = readDisassemblyOffset( cursorForWord );
I think that `offsetTo` should not be assigned with the current offset. As you mentioned in one of your comments.

2020-12-01 17:56 UTC, Petross404 commented on src/widgets/DisassemblyWidget.cpp
> +        QList<XrefDescription> refs = Core()->getXRefs( offsetTo, false, false);
I see your point. I will correct this and initialize the `offsetTo` with `RVA_INVALID` because basically at this point it is unknown.
```cpp
        RVA offsetFrom = readDisassemblyOffset(cursorForWord);
        RVA offsetTo = RVA_INVALID;
```

2020-12-01 17:56 UTC, Petross404 commented on src/widgets/DisassemblyWidget.cpp
> +            offsetFrom = refs.at(0).from;
Right, but do you think I should make a check like this?
```cpp
if(refs.at(0).from != offsetFrom){
    // Handle the error somehow?
}
```
Or is it redundant? Is there a case where this `if` could be true?

2020-12-01 17:59 UTC, Petross404 commented
> Hey @Petross404! We are deeply sorry for taking so much time to address your PR. Your details and explanations were great and you strictly followed the instructions and conventions we describe in the docs. The blame is on us.
> 
> I will address the PR today, and will ask other devs to have a look. Thank you so much!

No worries and thank you, I think my PR would be even better if the tooltip could be colored in a color that matched Cutter's or something.

2020-12-02 06:12 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +            offsetFrom = refs.at(0).from;
I am fine with such a check for verification :)

2020-12-02 06:13 UTC, ITAYC0HEN commented
Regarding colors, I thin that that's the Theme's default color. You can see that the tool tip when hovering on the navigation-map (top row) is with the same bg color. To improve how it looks, one needs to improve the themes :)

2020-12-02 07:35 UTC, Petross404 commented
> Regarding colors, I thin that that's the Theme's default color. You can see that the tool tip when hovering on the navigation-map (top row) is with the same bg color. To improve how it looks, one needs to improve the themes :)

Sure, you are right but function previews is white on my system. Anyway, I will come back for this in another time.

Before I remove the WIP and finish this I want to ask you two questions.

A) Should I squash the commits and make one for all of them?

B) After assigning the boolean flag `offsestDiffer` I construct fonts, QStrings and call `Core()->getDisassemblyPreview` even if the last check isn't gonna make it and show the tooltip.

Would it be better if we had something like:
```cpp
    if( offsetTo != offsetFrom ){
        // Remove the offsetsDiffer = true with nested ifs
        const QFont &fnt = Config()->getFont();
        QFontMetrics fm{ fnt };

        QString toolTipContent = QString("<html><div style=\"font-family: %1; font-size: %2pt; white-space: nowrap;\">")
               .arg(fnt.family()).arg(qMax(6, fnt.pointSize() - 1));

        QStringList disasmPreview = Core()->getDisassemblyPreview(offsetTo, 10);    
        //No need to check on offsetsDiffer here because offsetTo != offsetFrom has checked this above
        if (!disasmPreview.isEmpty() && offsetTo != RVA_INVALID){
             toolTipContent += tr("<div style=\"margin-bottom: 10px;\"><strong>Disassembly Preview</strong>:<br>%1<div>").arg(disasmPreview.join("<br>"));

             QToolTip::showText(helpEvent->globalPos(), toolTipContent, this, QRect(), 3500);
         }
    }
```
Of course we could use the old `offsetsDiff` in order to avoid nested ifs like this:
```cpp
....
            offsetTo = refs.at(0).to;

            if( offsetTo != offsetFrom ){
                offsetsDiffer = true;
            }
        }
       // No nested ifs
         if(offsetDiffer){
            //Now construct fonts, QStrings but we make the program run this check twice (offsetTo != offsetFrom is offsetDif) after all. 
```

Could we afford to save some cpu cycles against readability?

2020-12-02 10:28 UTC, ITAYC0HEN commented
> Should I squash the commits and make one for all of them?

Nah, we (github) will take care of it when we'll merge :)

Regarding the second point, I think that if you are not going to show a tooltip, you don't need to initialize the HTML for the tooltip itself. And thus, I think that the entire declaration and assignment of  `toolTipContent` should happen after you're sure the tooltip is going to be shown. Unless I missed anything. So it's a mixture of the options you wrote

> Could we afford to save some cpu cycles against readability?

Yes, we sure can. You can assist the reading by adding comments. In general, you have a free hand here to decide on the best approach to your opinion :)

2020-12-02 20:17 UTC, Petross404 commented
You guys are super helpfull and nice to work with. Let me know for any last minute fixes or changes you might want. I removed the WIP tag and unless you need something more, I am ok with the feature.

Sure I will keep an eye for further improvemets (mainly configuring it from settings). Also I thought about extending to GraphWidget too but that's another issue :)

2020-12-03 03:56 UTC, ITAYC0HEN requested changes
Great work! Only small things left and I think it is ready to go :tada:

2020-12-03 03:56 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +        //For future reference : https://github.com/radareorg/cutter/pull/2459
I'd remove this. That's why `git blame` is there :)

```suggestion
```

2020-12-03 03:56 UTC, ITAYC0HEN commented on src/widgets/DisassemblyWidget.cpp
> +                QString toolTipContent =
Any reason for this not the be inserted into the following if statement? If you define it and might never use it, then it is better to define it when you sure you'll do. 

So I guess that `QString toolTipContent` can be assigned once inside `if (!disasmPreview.isEmpty()) {`, and skip the `toolTipContent +=` part in favor of merging them together

2020-12-03 14:57 UTC, Petross404 commented on src/widgets/DisassemblyWidget.cpp
> +                QString toolTipContent =
> So I guess that QString toolTipContent can be assigned once inside if (!disasmPreview.isEmpty()) {, and skip the toolTipContent += part in favor of merging them together

I missed that part, I will fix it now.

2020-12-04 15:18 UTC, ITAYC0HEN approved these changes
Looks good to me! Well done @Petross404 :tada:

2020-12-05 02:00 UTC, Surendrajat approved these changes
Apart from the dark transparent shadow, it looks good. Nice work!

It can also be fixed in `QToolTip` entry in `src/themes/*/*.qss`.

2020-12-05 07:25 UTC, Petross404 commented
> Apart from the dark transparent shadow, it looks good. Nice work!
> 
> It can also be fixed in `QToolTip` entry in `src/themes/*/*.qss`.

I will experiment with this, nice idea.

2020-12-05 07:25 UTC, ITAYC0HEN approved these changes
I will merge this PR now, really good work!
Looking forward for your next contribution, it was a pleasure!

2020-12-05 07:26 UTC, merged