[WIP] Adding Labels to Graph Blocks in Disassembly
radareorg/cutter pull request #2482
Opened 2020-11-20 09:05 UTC by PulakIIIT

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Note: I am open to suggestions from the community for design and implementation choices as this is my first time contributing to the project

- Added block entry address as the header_text of Disassembly Block. (Prior to this change the header_text element was never modified anywhere else) 
- Used "offset" color from theme to display it
- Current Result:
<img width="1245" alt="Screenshot 2020-11-20 at 1 59 43 PM" src="https://user-images.githubusercontent.com/56169176/99780246-390b3500-2b3c-11eb-9f2d-de191367fb25.png">

- Currently Working on 
	- Making the entry address clickable and copyable
	- Adding support for custom string to label blocks 

**Test plan (required)**

**Closing issues**
Closes #1646

2020-11-20 17:48 UTC, karliss commented
Hi, my suggestion is making it an option in graph options page.

2020-11-21 09:06 UTC, PulakIIIT commented
Thanks for the suggestion. I have added it as a configuration option in Graphs pane in preferences.
<img width="876" alt="Screenshot 2020-11-21 at 2 35 07 PM" src="https://user-images.githubusercontent.com/56169176/99872286-cadf7480-2c06-11eb-9eb6-302a76b92224.png">
Checking and Unchecking the option instantly reflects the changes in the graph view

2020-11-21 11:34 UTC, karliss commented
I think it makes sense having it next to  "Show offsets" option and maybe elaborate label or tooltip for show offsets to help better distinguish the two options.

2020-11-22 07:33 UTC, PulakIIIT commented
I modified the graph options widget to make the layout and labels a bit more intuitive. I also added a tooltip for the graph block entry option label. 
<img width="900" alt="Screenshot 2020-11-22 at 12 37 34 PM" src="https://user-images.githubusercontent.com/56169176/99897480-d478e300-2cbf-11eb-82ab-a0e6d008224f.png">
Here is the tooltip
<img width="633" alt="Screenshot 2020-11-22 at 1 02 06 PM" src="https://user-images.githubusercontent.com/56169176/99897846-faec4d80-2cc2-11eb-8f0e-8dcf281d4f38.png">

2020-11-22 19:57 UTC, karliss commented
Once you feel it's ready remove the WIP/draft status and mark it as ready for review. Please also check the build errors in earlier commits. One of them happens in trunk, but one of them seems to be caused by your changes. Unfortunately travis builds aren't currently working, so it won't be possible to automatically verify the fix.

2020-11-26 18:01 UTC, karliss requested changes
Two small changes and it will be good to merge. I wanted to ask you to rebase your branch so that it gets run with latest CI fixes but looks like you already did it. :+1:

2020-11-27 10:16 UTC, PulakIIIT commented on src/common/Configuration.h
> +     * @brief Getter and setter for graph block entry offset
Apologies for the lazy documentation, I'll focus on writing better documentation in the future. Thanks for the constructive feedback.

2020-11-28 13:29 UTC, karliss commented on src/dialogs/preferences/GraphOptionsWidget.ui
>    <tabstop>horizontalBlockSpacing</tabstop>
If you don't know what you what this does please read https://doc.qt.io/qt-5/designer-tab-order.html . The current order still seems weird to me.

2020-11-29 14:39 UTC, karliss commented on src/common/Configuration.h
> +     * @brief Getter and setter for graph block entry offset
Don't worry about it too much. Sometimes there isn't anything to tell beside information already provided in function signature and common class documentation.

2020-11-29 14:41 UTC, merged

2020-11-29 16:30 UTC, ITAYC0HEN commented
Thank you @PulakIIIT ! Very nice work!
Looking forward to see more contributions from you, this is a very nice solution you made here! :smiley_cat: 
Let us know if there is anything we can help with

2020-12-01 08:32 UTC, PulakIIIT commented
You're welcome @ITAYC0HEN. Thanks @karliss for helping me out at every step!